/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TransactionResourceAttributesCashback type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionResourceAttributesCashback{}

// TransactionResourceAttributesCashback If all or part of this transaction was instantly reimbursed in the form of cashback, details of the reimbursement.
type TransactionResourceAttributesCashback struct {
	// A brief description of why this cashback was paid.
	Description string `json:"description"`
	// The total amount of cashback paid, represented as a positive value.
	Amount MoneyObject `json:"amount"`
}

type _TransactionResourceAttributesCashback TransactionResourceAttributesCashback

// NewTransactionResourceAttributesCashback instantiates a new TransactionResourceAttributesCashback object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionResourceAttributesCashback(description string, amount MoneyObject) *TransactionResourceAttributesCashback {
	this := TransactionResourceAttributesCashback{}
	this.Description = description
	this.Amount = amount
	return &this
}

// NewTransactionResourceAttributesCashbackWithDefaults instantiates a new TransactionResourceAttributesCashback object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionResourceAttributesCashbackWithDefaults() *TransactionResourceAttributesCashback {
	this := TransactionResourceAttributesCashback{}
	return &this
}

// GetDescription returns the Description field value
func (o *TransactionResourceAttributesCashback) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *TransactionResourceAttributesCashback) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *TransactionResourceAttributesCashback) SetDescription(v string) {
	o.Description = v
}

// GetAmount returns the Amount field value
func (o *TransactionResourceAttributesCashback) GetAmount() MoneyObject {
	if o == nil {
		var ret MoneyObject
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *TransactionResourceAttributesCashback) GetAmountOk() (*MoneyObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *TransactionResourceAttributesCashback) SetAmount(v MoneyObject) {
	o.Amount = v
}

func (o TransactionResourceAttributesCashback) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionResourceAttributesCashback) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	toSerialize["amount"] = o.Amount
	return toSerialize, nil
}

func (o *TransactionResourceAttributesCashback) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTransactionResourceAttributesCashback := _TransactionResourceAttributesCashback{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTransactionResourceAttributesCashback)

	if err != nil {
		return err
	}

	*o = TransactionResourceAttributesCashback(varTransactionResourceAttributesCashback)

	return err
}

type NullableTransactionResourceAttributesCashback struct {
	value *TransactionResourceAttributesCashback
	isSet bool
}

func (v NullableTransactionResourceAttributesCashback) Get() *TransactionResourceAttributesCashback {
	return v.value
}

func (v *NullableTransactionResourceAttributesCashback) Set(val *TransactionResourceAttributesCashback) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionResourceAttributesCashback) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionResourceAttributesCashback) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionResourceAttributesCashback(val *TransactionResourceAttributesCashback) *NullableTransactionResourceAttributesCashback {
	return &NullableTransactionResourceAttributesCashback{value: val, isSet: true}
}

func (v NullableTransactionResourceAttributesCashback) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionResourceAttributesCashback) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
