/*
Monzo API

The Monzo API is designed to be a predictable and intuitive interface for interacting with users' accounts. We offer both a REST API and webhooks.  The API implements OAuth 2.0 for authentication and provides access to accounts, transactions, pots, and more.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package monzoclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ReceiptItemSubItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReceiptItemSubItemsInner{}

// ReceiptItemSubItemsInner struct for ReceiptItemSubItemsInner
type ReceiptItemSubItemsInner struct {
	Description string   `json:"description"`
	Amount      int64    `json:"amount"`
	Currency    string   `json:"currency"`
	Quantity    *float64 `json:"quantity,omitempty"`
	Unit        *string  `json:"unit,omitempty"`
	Tax         *int64   `json:"tax,omitempty"`
}

type _ReceiptItemSubItemsInner ReceiptItemSubItemsInner

// NewReceiptItemSubItemsInner instantiates a new ReceiptItemSubItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReceiptItemSubItemsInner(description string, amount int64, currency string) *ReceiptItemSubItemsInner {
	this := ReceiptItemSubItemsInner{}
	this.Description = description
	this.Amount = amount
	this.Currency = currency
	return &this
}

// NewReceiptItemSubItemsInnerWithDefaults instantiates a new ReceiptItemSubItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReceiptItemSubItemsInnerWithDefaults() *ReceiptItemSubItemsInner {
	this := ReceiptItemSubItemsInner{}
	return &this
}

// GetDescription returns the Description field value
func (o *ReceiptItemSubItemsInner) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ReceiptItemSubItemsInner) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ReceiptItemSubItemsInner) SetDescription(v string) {
	o.Description = v
}

// GetAmount returns the Amount field value
func (o *ReceiptItemSubItemsInner) GetAmount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *ReceiptItemSubItemsInner) GetAmountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *ReceiptItemSubItemsInner) SetAmount(v int64) {
	o.Amount = v
}

// GetCurrency returns the Currency field value
func (o *ReceiptItemSubItemsInner) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *ReceiptItemSubItemsInner) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *ReceiptItemSubItemsInner) SetCurrency(v string) {
	o.Currency = v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *ReceiptItemSubItemsInner) GetQuantity() float64 {
	if o == nil || IsNil(o.Quantity) {
		var ret float64
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReceiptItemSubItemsInner) GetQuantityOk() (*float64, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *ReceiptItemSubItemsInner) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given float64 and assigns it to the Quantity field.
func (o *ReceiptItemSubItemsInner) SetQuantity(v float64) {
	o.Quantity = &v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *ReceiptItemSubItemsInner) GetUnit() string {
	if o == nil || IsNil(o.Unit) {
		var ret string
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReceiptItemSubItemsInner) GetUnitOk() (*string, bool) {
	if o == nil || IsNil(o.Unit) {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *ReceiptItemSubItemsInner) HasUnit() bool {
	if o != nil && !IsNil(o.Unit) {
		return true
	}

	return false
}

// SetUnit gets a reference to the given string and assigns it to the Unit field.
func (o *ReceiptItemSubItemsInner) SetUnit(v string) {
	o.Unit = &v
}

// GetTax returns the Tax field value if set, zero value otherwise.
func (o *ReceiptItemSubItemsInner) GetTax() int64 {
	if o == nil || IsNil(o.Tax) {
		var ret int64
		return ret
	}
	return *o.Tax
}

// GetTaxOk returns a tuple with the Tax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReceiptItemSubItemsInner) GetTaxOk() (*int64, bool) {
	if o == nil || IsNil(o.Tax) {
		return nil, false
	}
	return o.Tax, true
}

// HasTax returns a boolean if a field has been set.
func (o *ReceiptItemSubItemsInner) HasTax() bool {
	if o != nil && !IsNil(o.Tax) {
		return true
	}

	return false
}

// SetTax gets a reference to the given int64 and assigns it to the Tax field.
func (o *ReceiptItemSubItemsInner) SetTax(v int64) {
	o.Tax = &v
}

func (o ReceiptItemSubItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReceiptItemSubItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	toSerialize["amount"] = o.Amount
	toSerialize["currency"] = o.Currency
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.Unit) {
		toSerialize["unit"] = o.Unit
	}
	if !IsNil(o.Tax) {
		toSerialize["tax"] = o.Tax
	}
	return toSerialize, nil
}

func (o *ReceiptItemSubItemsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"amount",
		"currency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReceiptItemSubItemsInner := _ReceiptItemSubItemsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReceiptItemSubItemsInner)

	if err != nil {
		return err
	}

	*o = ReceiptItemSubItemsInner(varReceiptItemSubItemsInner)

	return err
}

type NullableReceiptItemSubItemsInner struct {
	value *ReceiptItemSubItemsInner
	isSet bool
}

func (v NullableReceiptItemSubItemsInner) Get() *ReceiptItemSubItemsInner {
	return v.value
}

func (v *NullableReceiptItemSubItemsInner) Set(val *ReceiptItemSubItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableReceiptItemSubItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableReceiptItemSubItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReceiptItemSubItemsInner(val *ReceiptItemSubItemsInner) *NullableReceiptItemSubItemsInner {
	return &NullableReceiptItemSubItemsInner{value: val, isSet: true}
}

func (v NullableReceiptItemSubItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReceiptItemSubItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
