/*
Monzo API

The Monzo API is designed to be a predictable and intuitive interface for interacting with users' accounts. We offer both a REST API and webhooks.  The API implements OAuth 2.0 for authentication and provides access to accounts, transactions, pots, and more.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package monzoclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Receipt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Receipt{}

// Receipt struct for Receipt
type Receipt struct {
	// The ID of the Transaction to associate the Receipt with
	TransactionId string `json:"transaction_id"`
	// A unique identifier used as an idempotency key
	ExternalId string `json:"external_id"`
	// The amount in minor units (pennies). Should be positive.
	Total int64 `json:"total"`
	// The currency code
	Currency string           `json:"currency"`
	Items    []ReceiptItem    `json:"items"`
	Taxes    []ReceiptTax     `json:"taxes,omitempty"`
	Payments []ReceiptPayment `json:"payments,omitempty"`
	Merchant *ReceiptMerchant `json:"merchant,omitempty"`
}

type _Receipt Receipt

// NewReceipt instantiates a new Receipt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReceipt(transactionId string, externalId string, total int64, currency string, items []ReceiptItem) *Receipt {
	this := Receipt{}
	this.TransactionId = transactionId
	this.ExternalId = externalId
	this.Total = total
	this.Currency = currency
	this.Items = items
	return &this
}

// NewReceiptWithDefaults instantiates a new Receipt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReceiptWithDefaults() *Receipt {
	this := Receipt{}
	return &this
}

// GetTransactionId returns the TransactionId field value
func (o *Receipt) GetTransactionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetTransactionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionId, true
}

// SetTransactionId sets field value
func (o *Receipt) SetTransactionId(v string) {
	o.TransactionId = v
}

// GetExternalId returns the ExternalId field value
func (o *Receipt) GetExternalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalId, true
}

// SetExternalId sets field value
func (o *Receipt) SetExternalId(v string) {
	o.ExternalId = v
}

// GetTotal returns the Total field value
func (o *Receipt) GetTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *Receipt) SetTotal(v int64) {
	o.Total = v
}

// GetCurrency returns the Currency field value
func (o *Receipt) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *Receipt) SetCurrency(v string) {
	o.Currency = v
}

// GetItems returns the Items field value
func (o *Receipt) GetItems() []ReceiptItem {
	if o == nil {
		var ret []ReceiptItem
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetItemsOk() ([]ReceiptItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *Receipt) SetItems(v []ReceiptItem) {
	o.Items = v
}

// GetTaxes returns the Taxes field value if set, zero value otherwise.
func (o *Receipt) GetTaxes() []ReceiptTax {
	if o == nil || IsNil(o.Taxes) {
		var ret []ReceiptTax
		return ret
	}
	return o.Taxes
}

// GetTaxesOk returns a tuple with the Taxes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetTaxesOk() ([]ReceiptTax, bool) {
	if o == nil || IsNil(o.Taxes) {
		return nil, false
	}
	return o.Taxes, true
}

// HasTaxes returns a boolean if a field has been set.
func (o *Receipt) HasTaxes() bool {
	if o != nil && !IsNil(o.Taxes) {
		return true
	}

	return false
}

// SetTaxes gets a reference to the given []ReceiptTax and assigns it to the Taxes field.
func (o *Receipt) SetTaxes(v []ReceiptTax) {
	o.Taxes = v
}

// GetPayments returns the Payments field value if set, zero value otherwise.
func (o *Receipt) GetPayments() []ReceiptPayment {
	if o == nil || IsNil(o.Payments) {
		var ret []ReceiptPayment
		return ret
	}
	return o.Payments
}

// GetPaymentsOk returns a tuple with the Payments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetPaymentsOk() ([]ReceiptPayment, bool) {
	if o == nil || IsNil(o.Payments) {
		return nil, false
	}
	return o.Payments, true
}

// HasPayments returns a boolean if a field has been set.
func (o *Receipt) HasPayments() bool {
	if o != nil && !IsNil(o.Payments) {
		return true
	}

	return false
}

// SetPayments gets a reference to the given []ReceiptPayment and assigns it to the Payments field.
func (o *Receipt) SetPayments(v []ReceiptPayment) {
	o.Payments = v
}

// GetMerchant returns the Merchant field value if set, zero value otherwise.
func (o *Receipt) GetMerchant() ReceiptMerchant {
	if o == nil || IsNil(o.Merchant) {
		var ret ReceiptMerchant
		return ret
	}
	return *o.Merchant
}

// GetMerchantOk returns a tuple with the Merchant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetMerchantOk() (*ReceiptMerchant, bool) {
	if o == nil || IsNil(o.Merchant) {
		return nil, false
	}
	return o.Merchant, true
}

// HasMerchant returns a boolean if a field has been set.
func (o *Receipt) HasMerchant() bool {
	if o != nil && !IsNil(o.Merchant) {
		return true
	}

	return false
}

// SetMerchant gets a reference to the given ReceiptMerchant and assigns it to the Merchant field.
func (o *Receipt) SetMerchant(v ReceiptMerchant) {
	o.Merchant = &v
}

func (o Receipt) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Receipt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["transaction_id"] = o.TransactionId
	toSerialize["external_id"] = o.ExternalId
	toSerialize["total"] = o.Total
	toSerialize["currency"] = o.Currency
	toSerialize["items"] = o.Items
	if !IsNil(o.Taxes) {
		toSerialize["taxes"] = o.Taxes
	}
	if !IsNil(o.Payments) {
		toSerialize["payments"] = o.Payments
	}
	if !IsNil(o.Merchant) {
		toSerialize["merchant"] = o.Merchant
	}
	return toSerialize, nil
}

func (o *Receipt) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"transaction_id",
		"external_id",
		"total",
		"currency",
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReceipt := _Receipt{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReceipt)

	if err != nil {
		return err
	}

	*o = Receipt(varReceipt)

	return err
}

type NullableReceipt struct {
	value *Receipt
	isSet bool
}

func (v NullableReceipt) Get() *Receipt {
	return v.value
}

func (v *NullableReceipt) Set(val *Receipt) {
	v.value = val
	v.isSet = true
}

func (v NullableReceipt) IsSet() bool {
	return v.isSet
}

func (v *NullableReceipt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReceipt(val *Receipt) *NullableReceipt {
	return &NullableReceipt{value: val, isSet: true}
}

func (v NullableReceipt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReceipt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
