/*
Monzo API

The Monzo API is designed to be a predictable and intuitive interface for interacting with users' accounts. We offer both a REST API and webhooks.  The API implements OAuth 2.0 for authentication and provides access to accounts, transactions, pots, and more.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package monzoclient

import (
	"encoding/json"
)

// checks if the BalanceResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BalanceResponse{}

// BalanceResponse struct for BalanceResponse
type BalanceResponse struct {
	// The currently available balance in minor units (pennies)
	Balance *int64 `json:"balance,omitempty"`
	// The sum of available balance and all pots
	TotalBalance *int64 `json:"total_balance,omitempty"`
	// The ISO 4217 currency code
	Currency *string `json:"currency,omitempty"`
	// The amount spent today (from ~4am) as a negative value
	SpendToday *int64 `json:"spend_today,omitempty"`
}

// NewBalanceResponse instantiates a new BalanceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBalanceResponse() *BalanceResponse {
	this := BalanceResponse{}
	return &this
}

// NewBalanceResponseWithDefaults instantiates a new BalanceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBalanceResponseWithDefaults() *BalanceResponse {
	this := BalanceResponse{}
	return &this
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *BalanceResponse) GetBalance() int64 {
	if o == nil || IsNil(o.Balance) {
		var ret int64
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BalanceResponse) GetBalanceOk() (*int64, bool) {
	if o == nil || IsNil(o.Balance) {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *BalanceResponse) HasBalance() bool {
	if o != nil && !IsNil(o.Balance) {
		return true
	}

	return false
}

// SetBalance gets a reference to the given int64 and assigns it to the Balance field.
func (o *BalanceResponse) SetBalance(v int64) {
	o.Balance = &v
}

// GetTotalBalance returns the TotalBalance field value if set, zero value otherwise.
func (o *BalanceResponse) GetTotalBalance() int64 {
	if o == nil || IsNil(o.TotalBalance) {
		var ret int64
		return ret
	}
	return *o.TotalBalance
}

// GetTotalBalanceOk returns a tuple with the TotalBalance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BalanceResponse) GetTotalBalanceOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalBalance) {
		return nil, false
	}
	return o.TotalBalance, true
}

// HasTotalBalance returns a boolean if a field has been set.
func (o *BalanceResponse) HasTotalBalance() bool {
	if o != nil && !IsNil(o.TotalBalance) {
		return true
	}

	return false
}

// SetTotalBalance gets a reference to the given int64 and assigns it to the TotalBalance field.
func (o *BalanceResponse) SetTotalBalance(v int64) {
	o.TotalBalance = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *BalanceResponse) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BalanceResponse) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *BalanceResponse) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *BalanceResponse) SetCurrency(v string) {
	o.Currency = &v
}

// GetSpendToday returns the SpendToday field value if set, zero value otherwise.
func (o *BalanceResponse) GetSpendToday() int64 {
	if o == nil || IsNil(o.SpendToday) {
		var ret int64
		return ret
	}
	return *o.SpendToday
}

// GetSpendTodayOk returns a tuple with the SpendToday field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BalanceResponse) GetSpendTodayOk() (*int64, bool) {
	if o == nil || IsNil(o.SpendToday) {
		return nil, false
	}
	return o.SpendToday, true
}

// HasSpendToday returns a boolean if a field has been set.
func (o *BalanceResponse) HasSpendToday() bool {
	if o != nil && !IsNil(o.SpendToday) {
		return true
	}

	return false
}

// SetSpendToday gets a reference to the given int64 and assigns it to the SpendToday field.
func (o *BalanceResponse) SetSpendToday(v int64) {
	o.SpendToday = &v
}

func (o BalanceResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BalanceResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Balance) {
		toSerialize["balance"] = o.Balance
	}
	if !IsNil(o.TotalBalance) {
		toSerialize["total_balance"] = o.TotalBalance
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.SpendToday) {
		toSerialize["spend_today"] = o.SpendToday
	}
	return toSerialize, nil
}

type NullableBalanceResponse struct {
	value *BalanceResponse
	isSet bool
}

func (v NullableBalanceResponse) Get() *BalanceResponse {
	return v.value
}

func (v *NullableBalanceResponse) Set(val *BalanceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBalanceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBalanceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBalanceResponse(val *BalanceResponse) *NullableBalanceResponse {
	return &NullableBalanceResponse{value: val, isSet: true}
}

func (v NullableBalanceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBalanceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
