/*
Monzo API

The Monzo API is designed to be a predictable and intuitive interface for interacting with users' accounts. We offer both a REST API and webhooks.  The API implements OAuth 2.0 for authentication and provides access to accounts, transactions, pots, and more.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package monzoclient

import (
	"encoding/json"
)

// checks if the RegisterWebhook200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterWebhook200Response{}

// RegisterWebhook200Response struct for RegisterWebhook200Response
type RegisterWebhook200Response struct {
	Webhook *Webhook `json:"webhook,omitempty"`
}

// NewRegisterWebhook200Response instantiates a new RegisterWebhook200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterWebhook200Response() *RegisterWebhook200Response {
	this := RegisterWebhook200Response{}
	return &this
}

// NewRegisterWebhook200ResponseWithDefaults instantiates a new RegisterWebhook200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterWebhook200ResponseWithDefaults() *RegisterWebhook200Response {
	this := RegisterWebhook200Response{}
	return &this
}

// GetWebhook returns the Webhook field value if set, zero value otherwise.
func (o *RegisterWebhook200Response) GetWebhook() Webhook {
	if o == nil || IsNil(o.Webhook) {
		var ret Webhook
		return ret
	}
	return *o.Webhook
}

// GetWebhookOk returns a tuple with the Webhook field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterWebhook200Response) GetWebhookOk() (*Webhook, bool) {
	if o == nil || IsNil(o.Webhook) {
		return nil, false
	}
	return o.Webhook, true
}

// HasWebhook returns a boolean if a field has been set.
func (o *RegisterWebhook200Response) HasWebhook() bool {
	if o != nil && !IsNil(o.Webhook) {
		return true
	}

	return false
}

// SetWebhook gets a reference to the given Webhook and assigns it to the Webhook field.
func (o *RegisterWebhook200Response) SetWebhook(v Webhook) {
	o.Webhook = &v
}

func (o RegisterWebhook200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterWebhook200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Webhook) {
		toSerialize["webhook"] = o.Webhook
	}
	return toSerialize, nil
}

type NullableRegisterWebhook200Response struct {
	value *RegisterWebhook200Response
	isSet bool
}

func (v NullableRegisterWebhook200Response) Get() *RegisterWebhook200Response {
	return v.value
}

func (v *NullableRegisterWebhook200Response) Set(val *RegisterWebhook200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterWebhook200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterWebhook200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterWebhook200Response(val *RegisterWebhook200Response) *NullableRegisterWebhook200Response {
	return &NullableRegisterWebhook200Response{value: val, isSet: true}
}

func (v NullableRegisterWebhook200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterWebhook200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
