/*
Monzo API

The Monzo API is designed to be a predictable and intuitive interface for interacting with users' accounts. We offer both a REST API and webhooks.  The API implements OAuth 2.0 for authentication and provides access to accounts, transactions, pots, and more.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package monzoclient

import (
	"encoding/json"
)

// checks if the ReceiptMerchant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReceiptMerchant{}

// ReceiptMerchant struct for ReceiptMerchant
type ReceiptMerchant struct {
	// The merchant name
	Name *string `json:"name,omitempty"`
	// True for e-commerce merchants, false for offline merchants
	Online *bool `json:"online,omitempty"`
	// The phone number of the store
	Phone *string `json:"phone,omitempty"`
	// The merchant's email address
	Email *string `json:"email,omitempty"`
	// The name of that particular store
	StoreName *string `json:"store_name,omitempty"`
	// The store's address
	StoreAddress *string `json:"store_address,omitempty"`
	// The store's postcode
	StorePostcode *string `json:"store_postcode,omitempty"`
}

// NewReceiptMerchant instantiates a new ReceiptMerchant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReceiptMerchant() *ReceiptMerchant {
	this := ReceiptMerchant{}
	return &this
}

// NewReceiptMerchantWithDefaults instantiates a new ReceiptMerchant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReceiptMerchantWithDefaults() *ReceiptMerchant {
	this := ReceiptMerchant{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ReceiptMerchant) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReceiptMerchant) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ReceiptMerchant) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ReceiptMerchant) SetName(v string) {
	o.Name = &v
}

// GetOnline returns the Online field value if set, zero value otherwise.
func (o *ReceiptMerchant) GetOnline() bool {
	if o == nil || IsNil(o.Online) {
		var ret bool
		return ret
	}
	return *o.Online
}

// GetOnlineOk returns a tuple with the Online field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReceiptMerchant) GetOnlineOk() (*bool, bool) {
	if o == nil || IsNil(o.Online) {
		return nil, false
	}
	return o.Online, true
}

// HasOnline returns a boolean if a field has been set.
func (o *ReceiptMerchant) HasOnline() bool {
	if o != nil && !IsNil(o.Online) {
		return true
	}

	return false
}

// SetOnline gets a reference to the given bool and assigns it to the Online field.
func (o *ReceiptMerchant) SetOnline(v bool) {
	o.Online = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *ReceiptMerchant) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReceiptMerchant) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *ReceiptMerchant) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *ReceiptMerchant) SetPhone(v string) {
	o.Phone = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *ReceiptMerchant) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReceiptMerchant) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *ReceiptMerchant) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *ReceiptMerchant) SetEmail(v string) {
	o.Email = &v
}

// GetStoreName returns the StoreName field value if set, zero value otherwise.
func (o *ReceiptMerchant) GetStoreName() string {
	if o == nil || IsNil(o.StoreName) {
		var ret string
		return ret
	}
	return *o.StoreName
}

// GetStoreNameOk returns a tuple with the StoreName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReceiptMerchant) GetStoreNameOk() (*string, bool) {
	if o == nil || IsNil(o.StoreName) {
		return nil, false
	}
	return o.StoreName, true
}

// HasStoreName returns a boolean if a field has been set.
func (o *ReceiptMerchant) HasStoreName() bool {
	if o != nil && !IsNil(o.StoreName) {
		return true
	}

	return false
}

// SetStoreName gets a reference to the given string and assigns it to the StoreName field.
func (o *ReceiptMerchant) SetStoreName(v string) {
	o.StoreName = &v
}

// GetStoreAddress returns the StoreAddress field value if set, zero value otherwise.
func (o *ReceiptMerchant) GetStoreAddress() string {
	if o == nil || IsNil(o.StoreAddress) {
		var ret string
		return ret
	}
	return *o.StoreAddress
}

// GetStoreAddressOk returns a tuple with the StoreAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReceiptMerchant) GetStoreAddressOk() (*string, bool) {
	if o == nil || IsNil(o.StoreAddress) {
		return nil, false
	}
	return o.StoreAddress, true
}

// HasStoreAddress returns a boolean if a field has been set.
func (o *ReceiptMerchant) HasStoreAddress() bool {
	if o != nil && !IsNil(o.StoreAddress) {
		return true
	}

	return false
}

// SetStoreAddress gets a reference to the given string and assigns it to the StoreAddress field.
func (o *ReceiptMerchant) SetStoreAddress(v string) {
	o.StoreAddress = &v
}

// GetStorePostcode returns the StorePostcode field value if set, zero value otherwise.
func (o *ReceiptMerchant) GetStorePostcode() string {
	if o == nil || IsNil(o.StorePostcode) {
		var ret string
		return ret
	}
	return *o.StorePostcode
}

// GetStorePostcodeOk returns a tuple with the StorePostcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReceiptMerchant) GetStorePostcodeOk() (*string, bool) {
	if o == nil || IsNil(o.StorePostcode) {
		return nil, false
	}
	return o.StorePostcode, true
}

// HasStorePostcode returns a boolean if a field has been set.
func (o *ReceiptMerchant) HasStorePostcode() bool {
	if o != nil && !IsNil(o.StorePostcode) {
		return true
	}

	return false
}

// SetStorePostcode gets a reference to the given string and assigns it to the StorePostcode field.
func (o *ReceiptMerchant) SetStorePostcode(v string) {
	o.StorePostcode = &v
}

func (o ReceiptMerchant) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReceiptMerchant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Online) {
		toSerialize["online"] = o.Online
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.StoreName) {
		toSerialize["store_name"] = o.StoreName
	}
	if !IsNil(o.StoreAddress) {
		toSerialize["store_address"] = o.StoreAddress
	}
	if !IsNil(o.StorePostcode) {
		toSerialize["store_postcode"] = o.StorePostcode
	}
	return toSerialize, nil
}

type NullableReceiptMerchant struct {
	value *ReceiptMerchant
	isSet bool
}

func (v NullableReceiptMerchant) Get() *ReceiptMerchant {
	return v.value
}

func (v *NullableReceiptMerchant) Set(val *ReceiptMerchant) {
	v.value = val
	v.isSet = true
}

func (v NullableReceiptMerchant) IsSet() bool {
	return v.isSet
}

func (v *NullableReceiptMerchant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReceiptMerchant(val *ReceiptMerchant) *NullableReceiptMerchant {
	return &NullableReceiptMerchant{value: val, isSet: true}
}

func (v NullableReceiptMerchant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReceiptMerchant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
