/*
Monzo API

The Monzo API is designed to be a predictable and intuitive interface for interacting with users' accounts. We offer both a REST API and webhooks.  The API implements OAuth 2.0 for authentication and provides access to accounts, transactions, pots, and more.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package monzoclient

import (
	"encoding/json"
)

// checks if the GetTransaction200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTransaction200Response{}

// GetTransaction200Response struct for GetTransaction200Response
type GetTransaction200Response struct {
	Transaction *Transaction `json:"transaction,omitempty"`
}

// NewGetTransaction200Response instantiates a new GetTransaction200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTransaction200Response() *GetTransaction200Response {
	this := GetTransaction200Response{}
	return &this
}

// NewGetTransaction200ResponseWithDefaults instantiates a new GetTransaction200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTransaction200ResponseWithDefaults() *GetTransaction200Response {
	this := GetTransaction200Response{}
	return &this
}

// GetTransaction returns the Transaction field value if set, zero value otherwise.
func (o *GetTransaction200Response) GetTransaction() Transaction {
	if o == nil || IsNil(o.Transaction) {
		var ret Transaction
		return ret
	}
	return *o.Transaction
}

// GetTransactionOk returns a tuple with the Transaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTransaction200Response) GetTransactionOk() (*Transaction, bool) {
	if o == nil || IsNil(o.Transaction) {
		return nil, false
	}
	return o.Transaction, true
}

// HasTransaction returns a boolean if a field has been set.
func (o *GetTransaction200Response) HasTransaction() bool {
	if o != nil && !IsNil(o.Transaction) {
		return true
	}

	return false
}

// SetTransaction gets a reference to the given Transaction and assigns it to the Transaction field.
func (o *GetTransaction200Response) SetTransaction(v Transaction) {
	o.Transaction = &v
}

func (o GetTransaction200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTransaction200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Transaction) {
		toSerialize["transaction"] = o.Transaction
	}
	return toSerialize, nil
}

type NullableGetTransaction200Response struct {
	value *GetTransaction200Response
	isSet bool
}

func (v NullableGetTransaction200Response) Get() *GetTransaction200Response {
	return v.value
}

func (v *NullableGetTransaction200Response) Set(val *GetTransaction200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTransaction200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTransaction200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTransaction200Response(val *GetTransaction200Response) *NullableGetTransaction200Response {
	return &NullableGetTransaction200Response{value: val, isSet: true}
}

func (v NullableGetTransaction200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTransaction200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
