/*
Monzo API

The Monzo API is designed to be a predictable and intuitive interface for interacting with users' accounts. We offer both a REST API and webhooks.  The API implements OAuth 2.0 for authentication and provides access to accounts, transactions, pots, and more.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package monzoclient

import (
	"encoding/json"
)

// checks if the WhoamiResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WhoamiResponse{}

// WhoamiResponse struct for WhoamiResponse
type WhoamiResponse struct {
	// Whether the request is authenticated
	Authenticated *bool `json:"authenticated,omitempty"`
	// Your client ID
	ClientId *string `json:"client_id,omitempty"`
	// The user ID
	UserId *string `json:"user_id,omitempty"`
}

// NewWhoamiResponse instantiates a new WhoamiResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhoamiResponse() *WhoamiResponse {
	this := WhoamiResponse{}
	return &this
}

// NewWhoamiResponseWithDefaults instantiates a new WhoamiResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhoamiResponseWithDefaults() *WhoamiResponse {
	this := WhoamiResponse{}
	return &this
}

// GetAuthenticated returns the Authenticated field value if set, zero value otherwise.
func (o *WhoamiResponse) GetAuthenticated() bool {
	if o == nil || IsNil(o.Authenticated) {
		var ret bool
		return ret
	}
	return *o.Authenticated
}

// GetAuthenticatedOk returns a tuple with the Authenticated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoamiResponse) GetAuthenticatedOk() (*bool, bool) {
	if o == nil || IsNil(o.Authenticated) {
		return nil, false
	}
	return o.Authenticated, true
}

// HasAuthenticated returns a boolean if a field has been set.
func (o *WhoamiResponse) HasAuthenticated() bool {
	if o != nil && !IsNil(o.Authenticated) {
		return true
	}

	return false
}

// SetAuthenticated gets a reference to the given bool and assigns it to the Authenticated field.
func (o *WhoamiResponse) SetAuthenticated(v bool) {
	o.Authenticated = &v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *WhoamiResponse) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoamiResponse) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *WhoamiResponse) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *WhoamiResponse) SetClientId(v string) {
	o.ClientId = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *WhoamiResponse) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoamiResponse) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *WhoamiResponse) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *WhoamiResponse) SetUserId(v string) {
	o.UserId = &v
}

func (o WhoamiResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WhoamiResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Authenticated) {
		toSerialize["authenticated"] = o.Authenticated
	}
	if !IsNil(o.ClientId) {
		toSerialize["client_id"] = o.ClientId
	}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	return toSerialize, nil
}

type NullableWhoamiResponse struct {
	value *WhoamiResponse
	isSet bool
}

func (v NullableWhoamiResponse) Get() *WhoamiResponse {
	return v.value
}

func (v *NullableWhoamiResponse) Set(val *WhoamiResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWhoamiResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWhoamiResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhoamiResponse(val *WhoamiResponse) *NullableWhoamiResponse {
	return &NullableWhoamiResponse{value: val, isSet: true}
}

func (v NullableWhoamiResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhoamiResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
