/*
Monzo API

The Monzo API is designed to be a predictable and intuitive interface for interacting with users' accounts. We offer both a REST API and webhooks.  The API implements OAuth 2.0 for authentication and provides access to accounts, transactions, pots, and more.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package monzoclient

import (
	"encoding/json"
)

// checks if the RegisterAttachment200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterAttachment200Response{}

// RegisterAttachment200Response struct for RegisterAttachment200Response
type RegisterAttachment200Response struct {
	Attachment *Attachment `json:"attachment,omitempty"`
}

// NewRegisterAttachment200Response instantiates a new RegisterAttachment200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterAttachment200Response() *RegisterAttachment200Response {
	this := RegisterAttachment200Response{}
	return &this
}

// NewRegisterAttachment200ResponseWithDefaults instantiates a new RegisterAttachment200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterAttachment200ResponseWithDefaults() *RegisterAttachment200Response {
	this := RegisterAttachment200Response{}
	return &this
}

// GetAttachment returns the Attachment field value if set, zero value otherwise.
func (o *RegisterAttachment200Response) GetAttachment() Attachment {
	if o == nil || IsNil(o.Attachment) {
		var ret Attachment
		return ret
	}
	return *o.Attachment
}

// GetAttachmentOk returns a tuple with the Attachment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterAttachment200Response) GetAttachmentOk() (*Attachment, bool) {
	if o == nil || IsNil(o.Attachment) {
		return nil, false
	}
	return o.Attachment, true
}

// HasAttachment returns a boolean if a field has been set.
func (o *RegisterAttachment200Response) HasAttachment() bool {
	if o != nil && !IsNil(o.Attachment) {
		return true
	}

	return false
}

// SetAttachment gets a reference to the given Attachment and assigns it to the Attachment field.
func (o *RegisterAttachment200Response) SetAttachment(v Attachment) {
	o.Attachment = &v
}

func (o RegisterAttachment200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterAttachment200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Attachment) {
		toSerialize["attachment"] = o.Attachment
	}
	return toSerialize, nil
}

type NullableRegisterAttachment200Response struct {
	value *RegisterAttachment200Response
	isSet bool
}

func (v NullableRegisterAttachment200Response) Get() *RegisterAttachment200Response {
	return v.value
}

func (v *NullableRegisterAttachment200Response) Set(val *RegisterAttachment200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterAttachment200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterAttachment200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterAttachment200Response(val *RegisterAttachment200Response) *NullableRegisterAttachment200Response {
	return &NullableRegisterAttachment200Response{value: val, isSet: true}
}

func (v NullableRegisterAttachment200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterAttachment200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
