/*
Monzo API

The Monzo API is designed to be a predictable and intuitive interface for interacting with users' accounts. We offer both a REST API and webhooks.  The API implements OAuth 2.0 for authentication and provides access to accounts, transactions, pots, and more.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package monzoclient

import (
	"encoding/json"
)

// checks if the AttachmentUploadResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AttachmentUploadResponse{}

// AttachmentUploadResponse struct for AttachmentUploadResponse
type AttachmentUploadResponse struct {
	// The URL of the file once it has been uploaded
	FileUrl *string `json:"file_url,omitempty"`
	// The URL to POST the file to when uploading
	UploadUrl *string `json:"upload_url,omitempty"`
}

// NewAttachmentUploadResponse instantiates a new AttachmentUploadResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttachmentUploadResponse() *AttachmentUploadResponse {
	this := AttachmentUploadResponse{}
	return &this
}

// NewAttachmentUploadResponseWithDefaults instantiates a new AttachmentUploadResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttachmentUploadResponseWithDefaults() *AttachmentUploadResponse {
	this := AttachmentUploadResponse{}
	return &this
}

// GetFileUrl returns the FileUrl field value if set, zero value otherwise.
func (o *AttachmentUploadResponse) GetFileUrl() string {
	if o == nil || IsNil(o.FileUrl) {
		var ret string
		return ret
	}
	return *o.FileUrl
}

// GetFileUrlOk returns a tuple with the FileUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttachmentUploadResponse) GetFileUrlOk() (*string, bool) {
	if o == nil || IsNil(o.FileUrl) {
		return nil, false
	}
	return o.FileUrl, true
}

// HasFileUrl returns a boolean if a field has been set.
func (o *AttachmentUploadResponse) HasFileUrl() bool {
	if o != nil && !IsNil(o.FileUrl) {
		return true
	}

	return false
}

// SetFileUrl gets a reference to the given string and assigns it to the FileUrl field.
func (o *AttachmentUploadResponse) SetFileUrl(v string) {
	o.FileUrl = &v
}

// GetUploadUrl returns the UploadUrl field value if set, zero value otherwise.
func (o *AttachmentUploadResponse) GetUploadUrl() string {
	if o == nil || IsNil(o.UploadUrl) {
		var ret string
		return ret
	}
	return *o.UploadUrl
}

// GetUploadUrlOk returns a tuple with the UploadUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttachmentUploadResponse) GetUploadUrlOk() (*string, bool) {
	if o == nil || IsNil(o.UploadUrl) {
		return nil, false
	}
	return o.UploadUrl, true
}

// HasUploadUrl returns a boolean if a field has been set.
func (o *AttachmentUploadResponse) HasUploadUrl() bool {
	if o != nil && !IsNil(o.UploadUrl) {
		return true
	}

	return false
}

// SetUploadUrl gets a reference to the given string and assigns it to the UploadUrl field.
func (o *AttachmentUploadResponse) SetUploadUrl(v string) {
	o.UploadUrl = &v
}

func (o AttachmentUploadResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AttachmentUploadResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FileUrl) {
		toSerialize["file_url"] = o.FileUrl
	}
	if !IsNil(o.UploadUrl) {
		toSerialize["upload_url"] = o.UploadUrl
	}
	return toSerialize, nil
}

type NullableAttachmentUploadResponse struct {
	value *AttachmentUploadResponse
	isSet bool
}

func (v NullableAttachmentUploadResponse) Get() *AttachmentUploadResponse {
	return v.value
}

func (v *NullableAttachmentUploadResponse) Set(val *AttachmentUploadResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAttachmentUploadResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAttachmentUploadResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttachmentUploadResponse(val *AttachmentUploadResponse) *NullableAttachmentUploadResponse {
	return &NullableAttachmentUploadResponse{value: val, isSet: true}
}

func (v NullableAttachmentUploadResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttachmentUploadResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
