services:
  app:
    image: expense-manager:latest
    container_name: expense-manager
    ports:
      - "8080:8080"
    environment:
      UP_BANK_TOKEN: ${UP_BANK_TOKEN}

secrets:
  UP_BANK_TOKEN:
    environment: ${UP_BANK_TOKEN:?error}
