/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package upclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AttachmentResourceRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AttachmentResourceRelationships{}

// AttachmentResourceRelationships struct for AttachmentResourceRelationships
type AttachmentResourceRelationships struct {
	Transaction AttachmentResourceRelationshipsTransaction `json:"transaction"`
}

type _AttachmentResourceRelationships AttachmentResourceRelationships

// NewAttachmentResourceRelationships instantiates a new AttachmentResourceRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttachmentResourceRelationships(transaction AttachmentResourceRelationshipsTransaction) *AttachmentResourceRelationships {
	this := AttachmentResourceRelationships{}
	this.Transaction = transaction
	return &this
}

// NewAttachmentResourceRelationshipsWithDefaults instantiates a new AttachmentResourceRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttachmentResourceRelationshipsWithDefaults() *AttachmentResourceRelationships {
	this := AttachmentResourceRelationships{}
	return &this
}

// GetTransaction returns the Transaction field value
func (o *AttachmentResourceRelationships) GetTransaction() AttachmentResourceRelationshipsTransaction {
	if o == nil {
		var ret AttachmentResourceRelationshipsTransaction
		return ret
	}

	return o.Transaction
}

// GetTransactionOk returns a tuple with the Transaction field value
// and a boolean to check if the value has been set.
func (o *AttachmentResourceRelationships) GetTransactionOk() (*AttachmentResourceRelationshipsTransaction, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Transaction, true
}

// SetTransaction sets field value
func (o *AttachmentResourceRelationships) SetTransaction(v AttachmentResourceRelationshipsTransaction) {
	o.Transaction = v
}

func (o AttachmentResourceRelationships) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AttachmentResourceRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["transaction"] = o.Transaction
	return toSerialize, nil
}

func (o *AttachmentResourceRelationships) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"transaction",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAttachmentResourceRelationships := _AttachmentResourceRelationships{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAttachmentResourceRelationships)

	if err != nil {
		return err
	}

	*o = AttachmentResourceRelationships(varAttachmentResourceRelationships)

	return err
}

type NullableAttachmentResourceRelationships struct {
	value *AttachmentResourceRelationships
	isSet bool
}

func (v NullableAttachmentResourceRelationships) Get() *AttachmentResourceRelationships {
	return v.value
}

func (v *NullableAttachmentResourceRelationships) Set(val *AttachmentResourceRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableAttachmentResourceRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableAttachmentResourceRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttachmentResourceRelationships(val *AttachmentResourceRelationships) *NullableAttachmentResourceRelationships {
	return &NullableAttachmentResourceRelationships{value: val, isSet: true}
}

func (v NullableAttachmentResourceRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttachmentResourceRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
