/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package upclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListAttachmentsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAttachmentsResponse{}

// ListAttachmentsResponse Successful response to get all attachments. This returns a paginated list of attachments, which can be scrolled by following the `prev` and `next` links if present. 
type ListAttachmentsResponse struct {
	// The list of attachments returned in this response. 
	Data []AttachmentResource `json:"data"`
	Links ListAccountsResponseLinks `json:"links"`
}

type _ListAttachmentsResponse ListAttachmentsResponse

// NewListAttachmentsResponse instantiates a new ListAttachmentsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAttachmentsResponse(data []AttachmentResource, links ListAccountsResponseLinks) *ListAttachmentsResponse {
	this := ListAttachmentsResponse{}
	this.Data = data
	this.Links = links
	return &this
}

// NewListAttachmentsResponseWithDefaults instantiates a new ListAttachmentsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAttachmentsResponseWithDefaults() *ListAttachmentsResponse {
	this := ListAttachmentsResponse{}
	return &this
}

// GetData returns the Data field value
func (o *ListAttachmentsResponse) GetData() []AttachmentResource {
	if o == nil {
		var ret []AttachmentResource
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListAttachmentsResponse) GetDataOk() ([]AttachmentResource, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListAttachmentsResponse) SetData(v []AttachmentResource) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *ListAttachmentsResponse) GetLinks() ListAccountsResponseLinks {
	if o == nil {
		var ret ListAccountsResponseLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *ListAttachmentsResponse) GetLinksOk() (*ListAccountsResponseLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *ListAttachmentsResponse) SetLinks(v ListAccountsResponseLinks) {
	o.Links = v
}

func (o ListAttachmentsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAttachmentsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *ListAttachmentsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListAttachmentsResponse := _ListAttachmentsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListAttachmentsResponse)

	if err != nil {
		return err
	}

	*o = ListAttachmentsResponse(varListAttachmentsResponse)

	return err
}

type NullableListAttachmentsResponse struct {
	value *ListAttachmentsResponse
	isSet bool
}

func (v NullableListAttachmentsResponse) Get() *ListAttachmentsResponse {
	return v.value
}

func (v *NullableListAttachmentsResponse) Set(val *ListAttachmentsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListAttachmentsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListAttachmentsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAttachmentsResponse(val *ListAttachmentsResponse) *NullableListAttachmentsResponse {
	return &NullableListAttachmentsResponse{value: val, isSet: true}
}

func (v NullableListAttachmentsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAttachmentsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


