/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package upclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the TransactionResourceAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionResourceAttributes{}

// TransactionResourceAttributes struct for TransactionResourceAttributes
type TransactionResourceAttributes struct {
	// The current processing status of this transaction, according to whether or not this transaction has settled or is still held. 
	Status TransactionStatusEnum `json:"status"`
	// The original, unprocessed text of the transaction. This is often not a perfect indicator of the actual merchant, but it is useful for reconciliation purposes in some cases. 
	RawText NullableString `json:"rawText"`
	// A short description for this transaction. Usually the merchant name for purchases. 
	Description string `json:"description"`
	// Attached message for this transaction, such as a payment message, or a transfer note. 
	Message NullableString `json:"message"`
	// Boolean flag set to true on transactions that support the use of categories. 
	IsCategorizable bool `json:"isCategorizable"`
	// If this transaction is currently in the `HELD` status, or was ever in the `HELD` status, the `amount` and `foreignAmount` of the transaction while `HELD`. 
	HoldInfo NullableHoldInfoObject `json:"holdInfo"`
	// Details of how this transaction was rounded-up. If no Round Up was applied this field will be `null`. 
	RoundUp NullableRoundUpObject `json:"roundUp"`
	// If all or part of this transaction was instantly reimbursed in the form of cashback, details of the reimbursement. 
	Cashback NullableCashbackObject `json:"cashback"`
	// The amount of this transaction in Australian dollars. For transactions that were once `HELD` but are now `SETTLED`, refer to the `holdInfo` field for the original `amount` the transaction was `HELD` at. 
	Amount MoneyObject `json:"amount"`
	// The foreign currency amount of this transaction. This field will be `null` for domestic transactions. The amount was converted to the AUD amount reflected in the `amount` of this transaction. Refer to the `holdInfo` field for the original `foreignAmount` the transaction was `HELD` at. 
	ForeignAmount NullableMoneyObject `json:"foreignAmount"`
	// Information about the card used for this transaction, if applicable. 
	CardPurchaseMethod NullableCardPurchaseMethodObject `json:"cardPurchaseMethod"`
	// The date-time at which this transaction settled. This field will be `null` for transactions that are currently in the `HELD` status. 
	SettledAt NullableTime `json:"settledAt"`
	// The date-time at which this transaction was first encountered. 
	CreatedAt time.Time `json:"createdAt"`
	// A description of the transaction method used e.g. Purchase, BPAY Payment. 
	TransactionType NullableString `json:"transactionType"`
	// A customer provided note about the transaction.  Can only be provided by Up High subscribers. 
	Note NullableNoteObject `json:"note"`
	// The customer who initated the transaction.  For 2Up accounts this could be the customer who's card was used. 
	PerformingCustomer NullableCustomerObject `json:"performingCustomer"`
	// A deep link to the transaction receipt screen in-app.
	DeepLinkURL NullableString `json:"deepLinkURL"`
}

type _TransactionResourceAttributes TransactionResourceAttributes

// NewTransactionResourceAttributes instantiates a new TransactionResourceAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionResourceAttributes(status TransactionStatusEnum, rawText NullableString, description string, message NullableString, isCategorizable bool, holdInfo NullableHoldInfoObject, roundUp NullableRoundUpObject, cashback NullableCashbackObject, amount MoneyObject, foreignAmount NullableMoneyObject, cardPurchaseMethod NullableCardPurchaseMethodObject, settledAt NullableTime, createdAt time.Time, transactionType NullableString, note NullableNoteObject, performingCustomer NullableCustomerObject, deepLinkURL NullableString) *TransactionResourceAttributes {
	this := TransactionResourceAttributes{}
	this.Status = status
	this.RawText = rawText
	this.Description = description
	this.Message = message
	this.IsCategorizable = isCategorizable
	this.HoldInfo = holdInfo
	this.RoundUp = roundUp
	this.Cashback = cashback
	this.Amount = amount
	this.ForeignAmount = foreignAmount
	this.CardPurchaseMethod = cardPurchaseMethod
	this.SettledAt = settledAt
	this.CreatedAt = createdAt
	this.TransactionType = transactionType
	this.Note = note
	this.PerformingCustomer = performingCustomer
	this.DeepLinkURL = deepLinkURL
	return &this
}

// NewTransactionResourceAttributesWithDefaults instantiates a new TransactionResourceAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionResourceAttributesWithDefaults() *TransactionResourceAttributes {
	this := TransactionResourceAttributes{}
	return &this
}

// GetStatus returns the Status field value
func (o *TransactionResourceAttributes) GetStatus() TransactionStatusEnum {
	if o == nil {
		var ret TransactionStatusEnum
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TransactionResourceAttributes) GetStatusOk() (*TransactionStatusEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TransactionResourceAttributes) SetStatus(v TransactionStatusEnum) {
	o.Status = v
}

// GetRawText returns the RawText field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TransactionResourceAttributes) GetRawText() string {
	if o == nil || o.RawText.Get() == nil {
		var ret string
		return ret
	}

	return *o.RawText.Get()
}

// GetRawTextOk returns a tuple with the RawText field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionResourceAttributes) GetRawTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RawText.Get(), o.RawText.IsSet()
}

// SetRawText sets field value
func (o *TransactionResourceAttributes) SetRawText(v string) {
	o.RawText.Set(&v)
}

// GetDescription returns the Description field value
func (o *TransactionResourceAttributes) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *TransactionResourceAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *TransactionResourceAttributes) SetDescription(v string) {
	o.Description = v
}

// GetMessage returns the Message field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TransactionResourceAttributes) GetMessage() string {
	if o == nil || o.Message.Get() == nil {
		var ret string
		return ret
	}

	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionResourceAttributes) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// SetMessage sets field value
func (o *TransactionResourceAttributes) SetMessage(v string) {
	o.Message.Set(&v)
}

// GetIsCategorizable returns the IsCategorizable field value
func (o *TransactionResourceAttributes) GetIsCategorizable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsCategorizable
}

// GetIsCategorizableOk returns a tuple with the IsCategorizable field value
// and a boolean to check if the value has been set.
func (o *TransactionResourceAttributes) GetIsCategorizableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsCategorizable, true
}

// SetIsCategorizable sets field value
func (o *TransactionResourceAttributes) SetIsCategorizable(v bool) {
	o.IsCategorizable = v
}

// GetHoldInfo returns the HoldInfo field value
// If the value is explicit nil, the zero value for HoldInfoObject will be returned
func (o *TransactionResourceAttributes) GetHoldInfo() HoldInfoObject {
	if o == nil || o.HoldInfo.Get() == nil {
		var ret HoldInfoObject
		return ret
	}

	return *o.HoldInfo.Get()
}

// GetHoldInfoOk returns a tuple with the HoldInfo field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionResourceAttributes) GetHoldInfoOk() (*HoldInfoObject, bool) {
	if o == nil {
		return nil, false
	}
	return o.HoldInfo.Get(), o.HoldInfo.IsSet()
}

// SetHoldInfo sets field value
func (o *TransactionResourceAttributes) SetHoldInfo(v HoldInfoObject) {
	o.HoldInfo.Set(&v)
}

// GetRoundUp returns the RoundUp field value
// If the value is explicit nil, the zero value for RoundUpObject will be returned
func (o *TransactionResourceAttributes) GetRoundUp() RoundUpObject {
	if o == nil || o.RoundUp.Get() == nil {
		var ret RoundUpObject
		return ret
	}

	return *o.RoundUp.Get()
}

// GetRoundUpOk returns a tuple with the RoundUp field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionResourceAttributes) GetRoundUpOk() (*RoundUpObject, bool) {
	if o == nil {
		return nil, false
	}
	return o.RoundUp.Get(), o.RoundUp.IsSet()
}

// SetRoundUp sets field value
func (o *TransactionResourceAttributes) SetRoundUp(v RoundUpObject) {
	o.RoundUp.Set(&v)
}

// GetCashback returns the Cashback field value
// If the value is explicit nil, the zero value for CashbackObject will be returned
func (o *TransactionResourceAttributes) GetCashback() CashbackObject {
	if o == nil || o.Cashback.Get() == nil {
		var ret CashbackObject
		return ret
	}

	return *o.Cashback.Get()
}

// GetCashbackOk returns a tuple with the Cashback field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionResourceAttributes) GetCashbackOk() (*CashbackObject, bool) {
	if o == nil {
		return nil, false
	}
	return o.Cashback.Get(), o.Cashback.IsSet()
}

// SetCashback sets field value
func (o *TransactionResourceAttributes) SetCashback(v CashbackObject) {
	o.Cashback.Set(&v)
}

// GetAmount returns the Amount field value
func (o *TransactionResourceAttributes) GetAmount() MoneyObject {
	if o == nil {
		var ret MoneyObject
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *TransactionResourceAttributes) GetAmountOk() (*MoneyObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *TransactionResourceAttributes) SetAmount(v MoneyObject) {
	o.Amount = v
}

// GetForeignAmount returns the ForeignAmount field value
// If the value is explicit nil, the zero value for MoneyObject will be returned
func (o *TransactionResourceAttributes) GetForeignAmount() MoneyObject {
	if o == nil || o.ForeignAmount.Get() == nil {
		var ret MoneyObject
		return ret
	}

	return *o.ForeignAmount.Get()
}

// GetForeignAmountOk returns a tuple with the ForeignAmount field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionResourceAttributes) GetForeignAmountOk() (*MoneyObject, bool) {
	if o == nil {
		return nil, false
	}
	return o.ForeignAmount.Get(), o.ForeignAmount.IsSet()
}

// SetForeignAmount sets field value
func (o *TransactionResourceAttributes) SetForeignAmount(v MoneyObject) {
	o.ForeignAmount.Set(&v)
}

// GetCardPurchaseMethod returns the CardPurchaseMethod field value
// If the value is explicit nil, the zero value for CardPurchaseMethodObject will be returned
func (o *TransactionResourceAttributes) GetCardPurchaseMethod() CardPurchaseMethodObject {
	if o == nil || o.CardPurchaseMethod.Get() == nil {
		var ret CardPurchaseMethodObject
		return ret
	}

	return *o.CardPurchaseMethod.Get()
}

// GetCardPurchaseMethodOk returns a tuple with the CardPurchaseMethod field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionResourceAttributes) GetCardPurchaseMethodOk() (*CardPurchaseMethodObject, bool) {
	if o == nil {
		return nil, false
	}
	return o.CardPurchaseMethod.Get(), o.CardPurchaseMethod.IsSet()
}

// SetCardPurchaseMethod sets field value
func (o *TransactionResourceAttributes) SetCardPurchaseMethod(v CardPurchaseMethodObject) {
	o.CardPurchaseMethod.Set(&v)
}

// GetSettledAt returns the SettledAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *TransactionResourceAttributes) GetSettledAt() time.Time {
	if o == nil || o.SettledAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.SettledAt.Get()
}

// GetSettledAtOk returns a tuple with the SettledAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionResourceAttributes) GetSettledAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.SettledAt.Get(), o.SettledAt.IsSet()
}

// SetSettledAt sets field value
func (o *TransactionResourceAttributes) SetSettledAt(v time.Time) {
	o.SettledAt.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *TransactionResourceAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *TransactionResourceAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *TransactionResourceAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetTransactionType returns the TransactionType field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TransactionResourceAttributes) GetTransactionType() string {
	if o == nil || o.TransactionType.Get() == nil {
		var ret string
		return ret
	}

	return *o.TransactionType.Get()
}

// GetTransactionTypeOk returns a tuple with the TransactionType field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionResourceAttributes) GetTransactionTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TransactionType.Get(), o.TransactionType.IsSet()
}

// SetTransactionType sets field value
func (o *TransactionResourceAttributes) SetTransactionType(v string) {
	o.TransactionType.Set(&v)
}

// GetNote returns the Note field value
// If the value is explicit nil, the zero value for NoteObject will be returned
func (o *TransactionResourceAttributes) GetNote() NoteObject {
	if o == nil || o.Note.Get() == nil {
		var ret NoteObject
		return ret
	}

	return *o.Note.Get()
}

// GetNoteOk returns a tuple with the Note field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionResourceAttributes) GetNoteOk() (*NoteObject, bool) {
	if o == nil {
		return nil, false
	}
	return o.Note.Get(), o.Note.IsSet()
}

// SetNote sets field value
func (o *TransactionResourceAttributes) SetNote(v NoteObject) {
	o.Note.Set(&v)
}

// GetPerformingCustomer returns the PerformingCustomer field value
// If the value is explicit nil, the zero value for CustomerObject will be returned
func (o *TransactionResourceAttributes) GetPerformingCustomer() CustomerObject {
	if o == nil || o.PerformingCustomer.Get() == nil {
		var ret CustomerObject
		return ret
	}

	return *o.PerformingCustomer.Get()
}

// GetPerformingCustomerOk returns a tuple with the PerformingCustomer field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionResourceAttributes) GetPerformingCustomerOk() (*CustomerObject, bool) {
	if o == nil {
		return nil, false
	}
	return o.PerformingCustomer.Get(), o.PerformingCustomer.IsSet()
}

// SetPerformingCustomer sets field value
func (o *TransactionResourceAttributes) SetPerformingCustomer(v CustomerObject) {
	o.PerformingCustomer.Set(&v)
}

// GetDeepLinkURL returns the DeepLinkURL field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TransactionResourceAttributes) GetDeepLinkURL() string {
	if o == nil || o.DeepLinkURL.Get() == nil {
		var ret string
		return ret
	}

	return *o.DeepLinkURL.Get()
}

// GetDeepLinkURLOk returns a tuple with the DeepLinkURL field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionResourceAttributes) GetDeepLinkURLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeepLinkURL.Get(), o.DeepLinkURL.IsSet()
}

// SetDeepLinkURL sets field value
func (o *TransactionResourceAttributes) SetDeepLinkURL(v string) {
	o.DeepLinkURL.Set(&v)
}

func (o TransactionResourceAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionResourceAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["rawText"] = o.RawText.Get()
	toSerialize["description"] = o.Description
	toSerialize["message"] = o.Message.Get()
	toSerialize["isCategorizable"] = o.IsCategorizable
	toSerialize["holdInfo"] = o.HoldInfo.Get()
	toSerialize["roundUp"] = o.RoundUp.Get()
	toSerialize["cashback"] = o.Cashback.Get()
	toSerialize["amount"] = o.Amount
	toSerialize["foreignAmount"] = o.ForeignAmount.Get()
	toSerialize["cardPurchaseMethod"] = o.CardPurchaseMethod.Get()
	toSerialize["settledAt"] = o.SettledAt.Get()
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["transactionType"] = o.TransactionType.Get()
	toSerialize["note"] = o.Note.Get()
	toSerialize["performingCustomer"] = o.PerformingCustomer.Get()
	toSerialize["deepLinkURL"] = o.DeepLinkURL.Get()
	return toSerialize, nil
}

func (o *TransactionResourceAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"rawText",
		"description",
		"message",
		"isCategorizable",
		"holdInfo",
		"roundUp",
		"cashback",
		"amount",
		"foreignAmount",
		"cardPurchaseMethod",
		"settledAt",
		"createdAt",
		"transactionType",
		"note",
		"performingCustomer",
		"deepLinkURL",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTransactionResourceAttributes := _TransactionResourceAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTransactionResourceAttributes)

	if err != nil {
		return err
	}

	*o = TransactionResourceAttributes(varTransactionResourceAttributes)

	return err
}

type NullableTransactionResourceAttributes struct {
	value *TransactionResourceAttributes
	isSet bool
}

func (v NullableTransactionResourceAttributes) Get() *TransactionResourceAttributes {
	return v.value
}

func (v *NullableTransactionResourceAttributes) Set(val *TransactionResourceAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionResourceAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionResourceAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionResourceAttributes(val *TransactionResourceAttributes) *NullableTransactionResourceAttributes {
	return &NullableTransactionResourceAttributes{value: val, isSet: true}
}

func (v NullableTransactionResourceAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionResourceAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


