/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package upclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RoundUpObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoundUpObject{}

// RoundUpObject Provides information about how a Round Up was applied, such as whether or not a boost was included in the Round Up.
type RoundUpObject struct {
	// The total amount of this Round Up, including any boosts, represented as a negative value.
	Amount MoneyObject `json:"amount"`
	// The portion of the Round Up `amount` owing to boosted Round Ups, represented as a negative value. If no boost was added to the Round Up this field will be `null`.
	BoostPortion NullableMoneyObject `json:"boostPortion"`
}

type _RoundUpObject RoundUpObject

// NewRoundUpObject instantiates a new RoundUpObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoundUpObject(amount MoneyObject, boostPortion NullableMoneyObject) *RoundUpObject {
	this := RoundUpObject{}
	this.Amount = amount
	this.BoostPortion = boostPortion
	return &this
}

// NewRoundUpObjectWithDefaults instantiates a new RoundUpObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoundUpObjectWithDefaults() *RoundUpObject {
	this := RoundUpObject{}
	return &this
}

// GetAmount returns the Amount field value
func (o *RoundUpObject) GetAmount() MoneyObject {
	if o == nil {
		var ret MoneyObject
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *RoundUpObject) GetAmountOk() (*MoneyObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *RoundUpObject) SetAmount(v MoneyObject) {
	o.Amount = v
}

// GetBoostPortion returns the BoostPortion field value
// If the value is explicit nil, the zero value for MoneyObject will be returned
func (o *RoundUpObject) GetBoostPortion() MoneyObject {
	if o == nil || o.BoostPortion.Get() == nil {
		var ret MoneyObject
		return ret
	}

	return *o.BoostPortion.Get()
}

// GetBoostPortionOk returns a tuple with the BoostPortion field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RoundUpObject) GetBoostPortionOk() (*MoneyObject, bool) {
	if o == nil {
		return nil, false
	}
	return o.BoostPortion.Get(), o.BoostPortion.IsSet()
}

// SetBoostPortion sets field value
func (o *RoundUpObject) SetBoostPortion(v MoneyObject) {
	o.BoostPortion.Set(&v)
}

func (o RoundUpObject) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoundUpObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amount"] = o.Amount
	toSerialize["boostPortion"] = o.BoostPortion.Get()
	return toSerialize, nil
}

func (o *RoundUpObject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amount",
		"boostPortion",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRoundUpObject := _RoundUpObject{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRoundUpObject)

	if err != nil {
		return err
	}

	*o = RoundUpObject(varRoundUpObject)

	return err
}

type NullableRoundUpObject struct {
	value *RoundUpObject
	isSet bool
}

func (v NullableRoundUpObject) Get() *RoundUpObject {
	return v.value
}

func (v *NullableRoundUpObject) Set(val *RoundUpObject) {
	v.value = val
	v.isSet = true
}

func (v NullableRoundUpObject) IsSet() bool {
	return v.isSet
}

func (v *NullableRoundUpObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoundUpObject(val *RoundUpObject) *NullableRoundUpObject {
	return &NullableRoundUpObject{value: val, isSet: true}
}

func (v NullableRoundUpObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoundUpObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
