/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TransactionResourceAttributesHoldInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionResourceAttributesHoldInfo{}

// TransactionResourceAttributesHoldInfo If this transaction is currently in the `HELD` status, or was ever in the `HELD` status, the `amount` and `foreignAmount` of the transaction while `HELD`.
type TransactionResourceAttributesHoldInfo struct {
	// The amount of this transaction while in the `HELD` status, in Australian dollars.
	Amount        MoneyObject                         `json:"amount"`
	ForeignAmount NullableHoldInfoObjectForeignAmount `json:"foreignAmount"`
}

type _TransactionResourceAttributesHoldInfo TransactionResourceAttributesHoldInfo

// NewTransactionResourceAttributesHoldInfo instantiates a new TransactionResourceAttributesHoldInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionResourceAttributesHoldInfo(amount MoneyObject, foreignAmount NullableHoldInfoObjectForeignAmount) *TransactionResourceAttributesHoldInfo {
	this := TransactionResourceAttributesHoldInfo{}
	this.Amount = amount
	this.ForeignAmount = foreignAmount
	return &this
}

// NewTransactionResourceAttributesHoldInfoWithDefaults instantiates a new TransactionResourceAttributesHoldInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionResourceAttributesHoldInfoWithDefaults() *TransactionResourceAttributesHoldInfo {
	this := TransactionResourceAttributesHoldInfo{}
	return &this
}

// GetAmount returns the Amount field value
func (o *TransactionResourceAttributesHoldInfo) GetAmount() MoneyObject {
	if o == nil {
		var ret MoneyObject
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *TransactionResourceAttributesHoldInfo) GetAmountOk() (*MoneyObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *TransactionResourceAttributesHoldInfo) SetAmount(v MoneyObject) {
	o.Amount = v
}

// GetForeignAmount returns the ForeignAmount field value
// If the value is explicit nil, the zero value for HoldInfoObjectForeignAmount will be returned
func (o *TransactionResourceAttributesHoldInfo) GetForeignAmount() HoldInfoObjectForeignAmount {
	if o == nil || o.ForeignAmount.Get() == nil {
		var ret HoldInfoObjectForeignAmount
		return ret
	}

	return *o.ForeignAmount.Get()
}

// GetForeignAmountOk returns a tuple with the ForeignAmount field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionResourceAttributesHoldInfo) GetForeignAmountOk() (*HoldInfoObjectForeignAmount, bool) {
	if o == nil {
		return nil, false
	}
	return o.ForeignAmount.Get(), o.ForeignAmount.IsSet()
}

// SetForeignAmount sets field value
func (o *TransactionResourceAttributesHoldInfo) SetForeignAmount(v HoldInfoObjectForeignAmount) {
	o.ForeignAmount.Set(&v)
}

func (o TransactionResourceAttributesHoldInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionResourceAttributesHoldInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amount"] = o.Amount
	toSerialize["foreignAmount"] = o.ForeignAmount.Get()
	return toSerialize, nil
}

func (o *TransactionResourceAttributesHoldInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amount",
		"foreignAmount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTransactionResourceAttributesHoldInfo := _TransactionResourceAttributesHoldInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTransactionResourceAttributesHoldInfo)

	if err != nil {
		return err
	}

	*o = TransactionResourceAttributesHoldInfo(varTransactionResourceAttributesHoldInfo)

	return err
}

type NullableTransactionResourceAttributesHoldInfo struct {
	value *TransactionResourceAttributesHoldInfo
	isSet bool
}

func (v NullableTransactionResourceAttributesHoldInfo) Get() *TransactionResourceAttributesHoldInfo {
	return v.value
}

func (v *NullableTransactionResourceAttributesHoldInfo) Set(val *TransactionResourceAttributesHoldInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionResourceAttributesHoldInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionResourceAttributesHoldInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionResourceAttributesHoldInfo(val *TransactionResourceAttributesHoldInfo) *NullableTransactionResourceAttributesHoldInfo {
	return &NullableTransactionResourceAttributesHoldInfo{value: val, isSet: true}
}

func (v NullableTransactionResourceAttributesHoldInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionResourceAttributesHoldInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
