/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ListCategoriesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListCategoriesResponse{}

// ListCategoriesResponse Successful response to get all categories and their ancestry. The returned list is not paginated.
type ListCategoriesResponse struct {
	// The list of categories returned in this response.
	Data []CategoryResource `json:"data"`
}

type _ListCategoriesResponse ListCategoriesResponse

// NewListCategoriesResponse instantiates a new ListCategoriesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListCategoriesResponse(data []CategoryResource) *ListCategoriesResponse {
	this := ListCategoriesResponse{}
	this.Data = data
	return &this
}

// NewListCategoriesResponseWithDefaults instantiates a new ListCategoriesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListCategoriesResponseWithDefaults() *ListCategoriesResponse {
	this := ListCategoriesResponse{}
	return &this
}

// GetData returns the Data field value
func (o *ListCategoriesResponse) GetData() []CategoryResource {
	if o == nil {
		var ret []CategoryResource
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListCategoriesResponse) GetDataOk() ([]CategoryResource, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListCategoriesResponse) SetData(v []CategoryResource) {
	o.Data = v
}

func (o ListCategoriesResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListCategoriesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ListCategoriesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListCategoriesResponse := _ListCategoriesResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListCategoriesResponse)

	if err != nil {
		return err
	}

	*o = ListCategoriesResponse(varListCategoriesResponse)

	return err
}

type NullableListCategoriesResponse struct {
	value *ListCategoriesResponse
	isSet bool
}

func (v NullableListCategoriesResponse) Get() *ListCategoriesResponse {
	return v.value
}

func (v *NullableListCategoriesResponse) Set(val *ListCategoriesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListCategoriesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListCategoriesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListCategoriesResponse(val *ListCategoriesResponse) *NullableListCategoriesResponse {
	return &NullableListCategoriesResponse{value: val, isSet: true}
}

func (v NullableListCategoriesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListCategoriesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
