/*
Up API

Testing TagsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapiclient

import (
	"context"
	openapiclient "github.com/esteanes/expense-manager/datafetcher/openapiclient"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapiclient_TagsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TagsAPIService TagsGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.TagsAPI.TagsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TagsAPIService TransactionsTransactionIdRelationshipsTagsDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var transactionId string

		httpRes, err := apiClient.TagsAPI.TransactionsTransactionIdRelationshipsTagsDelete(context.Background(), transactionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TagsAPIService TransactionsTransactionIdRelationshipsTagsPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var transactionId string

		httpRes, err := apiClient.TagsAPI.TransactionsTransactionIdRelationshipsTagsPost(context.Background(), transactionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
