/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AccountResourceRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountResourceRelationships{}

// AccountResourceRelationships struct for AccountResourceRelationships
type AccountResourceRelationships struct {
	Transactions AccountResourceRelationshipsTransactions `json:"transactions"`
}

type _AccountResourceRelationships AccountResourceRelationships

// NewAccountResourceRelationships instantiates a new AccountResourceRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountResourceRelationships(transactions AccountResourceRelationshipsTransactions) *AccountResourceRelationships {
	this := AccountResourceRelationships{}
	this.Transactions = transactions
	return &this
}

// NewAccountResourceRelationshipsWithDefaults instantiates a new AccountResourceRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountResourceRelationshipsWithDefaults() *AccountResourceRelationships {
	this := AccountResourceRelationships{}
	return &this
}

// GetTransactions returns the Transactions field value
func (o *AccountResourceRelationships) GetTransactions() AccountResourceRelationshipsTransactions {
	if o == nil {
		var ret AccountResourceRelationshipsTransactions
		return ret
	}

	return o.Transactions
}

// GetTransactionsOk returns a tuple with the Transactions field value
// and a boolean to check if the value has been set.
func (o *AccountResourceRelationships) GetTransactionsOk() (*AccountResourceRelationshipsTransactions, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Transactions, true
}

// SetTransactions sets field value
func (o *AccountResourceRelationships) SetTransactions(v AccountResourceRelationshipsTransactions) {
	o.Transactions = v
}

func (o AccountResourceRelationships) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountResourceRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["transactions"] = o.Transactions
	return toSerialize, nil
}

func (o *AccountResourceRelationships) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"transactions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccountResourceRelationships := _AccountResourceRelationships{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccountResourceRelationships)

	if err != nil {
		return err
	}

	*o = AccountResourceRelationships(varAccountResourceRelationships)

	return err
}

type NullableAccountResourceRelationships struct {
	value *AccountResourceRelationships
	isSet bool
}

func (v NullableAccountResourceRelationships) Get() *AccountResourceRelationships {
	return v.value
}

func (v *NullableAccountResourceRelationships) Set(val *AccountResourceRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountResourceRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountResourceRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountResourceRelationships(val *AccountResourceRelationships) *NullableAccountResourceRelationships {
	return &NullableAccountResourceRelationships{value: val, isSet: true}
}

func (v NullableAccountResourceRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountResourceRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
