/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WebhookEventResourceRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookEventResourceRelationships{}

// WebhookEventResourceRelationships struct for WebhookEventResourceRelationships
type WebhookEventResourceRelationships struct {
	Webhook     WebhookEventResourceRelationshipsWebhook      `json:"webhook"`
	Transaction *WebhookEventResourceRelationshipsTransaction `json:"transaction,omitempty"`
}

type _WebhookEventResourceRelationships WebhookEventResourceRelationships

// NewWebhookEventResourceRelationships instantiates a new WebhookEventResourceRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookEventResourceRelationships(webhook WebhookEventResourceRelationshipsWebhook) *WebhookEventResourceRelationships {
	this := WebhookEventResourceRelationships{}
	this.Webhook = webhook
	return &this
}

// NewWebhookEventResourceRelationshipsWithDefaults instantiates a new WebhookEventResourceRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookEventResourceRelationshipsWithDefaults() *WebhookEventResourceRelationships {
	this := WebhookEventResourceRelationships{}
	return &this
}

// GetWebhook returns the Webhook field value
func (o *WebhookEventResourceRelationships) GetWebhook() WebhookEventResourceRelationshipsWebhook {
	if o == nil {
		var ret WebhookEventResourceRelationshipsWebhook
		return ret
	}

	return o.Webhook
}

// GetWebhookOk returns a tuple with the Webhook field value
// and a boolean to check if the value has been set.
func (o *WebhookEventResourceRelationships) GetWebhookOk() (*WebhookEventResourceRelationshipsWebhook, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Webhook, true
}

// SetWebhook sets field value
func (o *WebhookEventResourceRelationships) SetWebhook(v WebhookEventResourceRelationshipsWebhook) {
	o.Webhook = v
}

// GetTransaction returns the Transaction field value if set, zero value otherwise.
func (o *WebhookEventResourceRelationships) GetTransaction() WebhookEventResourceRelationshipsTransaction {
	if o == nil || IsNil(o.Transaction) {
		var ret WebhookEventResourceRelationshipsTransaction
		return ret
	}
	return *o.Transaction
}

// GetTransactionOk returns a tuple with the Transaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEventResourceRelationships) GetTransactionOk() (*WebhookEventResourceRelationshipsTransaction, bool) {
	if o == nil || IsNil(o.Transaction) {
		return nil, false
	}
	return o.Transaction, true
}

// HasTransaction returns a boolean if a field has been set.
func (o *WebhookEventResourceRelationships) HasTransaction() bool {
	if o != nil && !IsNil(o.Transaction) {
		return true
	}

	return false
}

// SetTransaction gets a reference to the given WebhookEventResourceRelationshipsTransaction and assigns it to the Transaction field.
func (o *WebhookEventResourceRelationships) SetTransaction(v WebhookEventResourceRelationshipsTransaction) {
	o.Transaction = &v
}

func (o WebhookEventResourceRelationships) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookEventResourceRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["webhook"] = o.Webhook
	if !IsNil(o.Transaction) {
		toSerialize["transaction"] = o.Transaction
	}
	return toSerialize, nil
}

func (o *WebhookEventResourceRelationships) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"webhook",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookEventResourceRelationships := _WebhookEventResourceRelationships{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookEventResourceRelationships)

	if err != nil {
		return err
	}

	*o = WebhookEventResourceRelationships(varWebhookEventResourceRelationships)

	return err
}

type NullableWebhookEventResourceRelationships struct {
	value *WebhookEventResourceRelationships
	isSet bool
}

func (v NullableWebhookEventResourceRelationships) Get() *WebhookEventResourceRelationships {
	return v.value
}

func (v *NullableWebhookEventResourceRelationships) Set(val *WebhookEventResourceRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookEventResourceRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookEventResourceRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookEventResourceRelationships(val *WebhookEventResourceRelationships) *NullableWebhookEventResourceRelationships {
	return &NullableWebhookEventResourceRelationships{value: val, isSet: true}
}

func (v NullableWebhookEventResourceRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookEventResourceRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
