/*
Monzo API

Testing PotsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package monzoclient

import (
	"context"
	openapiclient "github.com/esteanes/up-bank-go/datafetcher/monzoclient"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_monzoclient_PotsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PotsAPIService DepositIntoPot", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var potId string

		resp, httpRes, err := apiClient.PotsAPI.DepositIntoPot(context.Background(), potId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PotsAPIService ListPots", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.PotsAPI.ListPots(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PotsAPIService WithdrawFromPot", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var potId string

		resp, httpRes, err := apiClient.PotsAPI.WithdrawFromPot(context.Background(), potId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
